= Introduction

{this-platform} {this-application} is extensions to cloudhopper smpp stack with adding of management for ESMEs and ESME clusters with CLI and GUI access.

{this-platform} {this-application} comes with JSLEE SMPP Resource Adaptors (RA) that enable developers to build SMPP applications with ease.
Developers only require an understanding of Resource Adaptors and can focus on building applications quickly and efficiently rather than worry about the SMPP stack.

If you wish to use JSLEE Resource Adapters, the Command Line Interface (CLI - Shell Management tool) or the GUI for run-time configuration, then you must have JBoss Application Server installed and running.
However if you do not wish to use the Resource Adaptors or CLI then {this-platform} {this-application} can work as a standalone library. In this case you need to make your own implementation of classes that was implemented at SMPP RA level.

The Open Source Software gives you the flexibility to understand the readily available source code and customise the product for your Enterprise needs. 

This guide will assist you in installing {this-platform} {this-application} .
For more details on configuring and using the platform or for information regarding the supported protocols and compliant standards, please refer to the {this-platform} {this-application} User Guide.
 
